export const SITE_CONFIG = {
  name: "BuildForce - Construction Recruitment & Workforce Platform",
  shortName: "BuildForce",
  url: "https://buildforce.com",
  description:
    "India's leading construction recruitment and workforce management platform. Connecting students, skilled workers, contractors, and construction companies. Find construction jobs, hire skilled workers, post projects, and grow your career in the construction industry.",
  ogImage: "https://buildforce.com/og-image.png",
  twitter: "@buildforce",
  author: "BuildForce",
  email: "hello@buildforce.com",
  careersEmail: "careers@buildforce.com",
  supportEmail: "support@buildforce.com",
  phone: "+91 80000 00000",
  address: {
    street: "Tech Park, Bopal",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    zip: "380058",
  },
  socials: {
    twitter: "https://twitter.com/buildforce",
    linkedin: "https://linkedin.com/company/buildforce",
    facebook: "https://facebook.com/buildforce",
    instagram: "https://instagram.com/buildforce",
    youtube: "https://youtube.com/@buildforce",
  },
  keywords: [
    "Construction Jobs",
    "Construction Recruitment",
    "Construction Workers",
    "Hire Construction Workers",
    "Skilled Labor",
    "Mason Jobs",
    "Electrician Jobs",
    "Plumber Jobs",
    "Carpenter Jobs",
    "Welder Jobs",
    "Construction Internships",
    "Civil Engineering Jobs",
    "Site Engineer Jobs",
    "Construction Companies",
    "Contractors",
    "Construction Projects",
    "Workforce Management",
    "Construction Bidding",
    "Building Projects",
    "Infrastructure Jobs",
    "Construction Career",
    "Site Supervisor Jobs",
  ],
} as const

export type SiteConfig = typeof SITE_CONFIG